### ISSUE TITLE
Create Barplot Generating Script for Juvenile HFD RNAseq

### ISSUE THREAD

**Issue by davebridges** [BridgesLab/PredictorsDietInducedObesity#37]
Can you create a barplots script to generate some graphs of these data

I think the best thing would be to have separate gene lists for muscle and adipose and then to show the CD/HFD bars colored differently beside each other with fed and fasted on different x-axis locations.  I would guess the acromegaly or Cushing's scripts should work, but my first pass couldn't get them to run.

**Comment by qtran1** [comment]
Ok! I will do that!

Quynh T. Tran, PhD

On Aug 10, 2015, at 5:32 PM, Dave Bridges <notifications@github.com<mailto:notifications@github.com>> wrote:


Can you create a barplots script to generate some graphs of these data

I think the best thing would be to have separate gene lists for muscle and adipose and then to show the CD/HFD bars colored differently beside each other with fed and fasted on different x-axis locations. I would guess the acromegaly or Cushing's scripts should work, but my first pass couldn't get them to run.

**Comment by davebridges** [comment]
Did this for both HTseq and kallisto, see commits 377457b and 552481b
